/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class exampleJNI {
  public final static native long new_FullNameVector__SWIG_0();
  public final static native long new_FullNameVector__SWIG_1(long jarg1, FullNameVector jarg1_);
  public final static native boolean FullNameVector_isEmpty(long jarg1, FullNameVector jarg1_);
  public final static native void FullNameVector_clear(long jarg1, FullNameVector jarg1_);
  public final static native long new_FullNameVector__SWIG_2(int jarg1, long jarg2, FullName jarg2_);
  public final static native int FullNameVector_doCapacity(long jarg1, FullNameVector jarg1_);
  public final static native void FullNameVector_doReserve(long jarg1, FullNameVector jarg1_, int jarg2);
  public final static native int FullNameVector_doSize(long jarg1, FullNameVector jarg1_);
  public final static native void FullNameVector_doAdd__SWIG_0(long jarg1, FullNameVector jarg1_, long jarg2, FullName jarg2_);
  public final static native void FullNameVector_doAdd__SWIG_1(long jarg1, FullNameVector jarg1_, int jarg2, long jarg3, FullName jarg3_);
  public final static native long FullNameVector_doRemove(long jarg1, FullNameVector jarg1_, int jarg2);
  public final static native long FullNameVector_doGet(long jarg1, FullNameVector jarg1_, int jarg2);
  public final static native long FullNameVector_doSet(long jarg1, FullNameVector jarg1_, int jarg2, long jarg3, FullName jarg3_);
  public final static native void FullNameVector_doRemoveRange(long jarg1, FullNameVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_FullNameVector(long jarg1);
  public final static native void FullName_first_name_set(long jarg1, FullName jarg1_, String jarg2);
  public final static native String FullName_first_name_get(long jarg1, FullName jarg1_);
  public final static native void FullName_last_name_set(long jarg1, FullName jarg1_, String jarg2);
  public final static native String FullName_last_name_get(long jarg1, FullName jarg1_);
  public final static native long new_FullName(String jarg1, String jarg2);
  public final static native void delete_FullName(long jarg1);
  public final static native long getNames();
  public final static native void printAllNames(long jarg1, FullNameVector jarg1_);
}
