/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static FullNameVector getNames() {
    return new FullNameVector(exampleJNI.getNames(), true);
  }

  public static void printAllNames(FullNameVector names) {
    exampleJNI.printAllNames(FullNameVector.getCPtr(names), names);
  }

}
